In [1]:
import pandas as pd
from pycaret.regression import setup, compare_models, blend_models, finalize_model, plot_model, predict_model, add_metric, evaluate_model

In [2]:
main_train_data = pd.read_csv("HW_train_main_data.csv", parse_dates=["timestamp"])
main_test_data = pd.read_csv("HW_test_main_data.csv", parse_dates=["timestamp"])

main_train_data = main_train_data.sort_values(by=["timestamp"])
main_test_data = main_test_data.sort_values(by=["timestamp"])

In [3]:
main_train_data

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,apartment condition,sub_area,price
1733,84150,2011-09-06,35,19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,70,6006000.0
22408,93255,2011-09-14,80,77.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,6,17001000.0
7361,44634,2011-09-14,43,27.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,44,5649800.0
27351,18855,2011-09-16,45,44.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,9,2068000.0
14731,65431,2011-09-16,67,46.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,73,9982700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4260,51270,2015-07-30,56,51.0,19.0,19.0,1.0,2017.0,2.0,1.0,1.0,127,11318900.0
5727,20074,2015-07-30,48,47.0,7.0,25.0,1.0,2015.0,1.0,1.0,1.0,24,9624400.0
26154,34576,2015-07-31,51,NaN,4.0,17.0,4.0,NaN,2.0,1.0,1.0,124,5946400.0
22365,74488,2015-07-31,76,NaN,8.0,17.0,1.0,NaN,3.0,1.0,NaN,94,7294500.0
5131,58320,2015-07-31,66,NaN,15.0,17.0,1.0,NaN,2.0,1.0,NaN,124,6328700.0

In [7]:
setup(data=main_train_data,
          target="price",
          fold = 5)

best = compare_models(sort = 'RMSE')

pred = predict_model(best, main_test_data)

In [6]:
setup(data=main_train_data.drop(['id'], axis = 1),
          target="price",
          fold = 5)

best = compare_models(sort = 'RMSE')

pred = predict_model(best, main_test_data.drop(['id'], axis = 1),)

In [16]:
pred = pred.sort_values(by=["id"])
pred = pred.rename(columns={"prediction_label":"predicted_price"}).reset_index()
pred[["id","predicted_price"]].to_csv('baseline.csv', index=False)